### ISSUE TITLE
parser does not include body in put request

### ISSUE THREAD

**Issue by WAvdBeek** [an2deg/pyraml-parser#12]
example of an RAML put where the body of the put is not in the parse tree:

#%RAML 0.8
title: putexample
version: v1.0

/putexample:
    put:
      body:
        application/json:
          schema: |
              { "$schema": "http://json-schema.org/schema",
                "value" : { "type": "boolean" }
              } 
      responses:    
        200:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  
                  "value" : { "type": "boolean" }
                }
              example: |
                { 
                  "value": "true"
                }       

output from the parser:
(it sees the body, but does not fill an body object in the resulting tree, since the expected  body at tree level is "None", Hence the parsing of the body fails ??).
parse_body: <pyraml.parser.ParseContext object at 0x02C088F0> {'application/json': {'schema': '{ "$schema": "http://json
-schema.org/schema",\n  "value" : { "type": "boolean" }\n} \n'}}
None
parse_body: {'body': None, 'is_': None, 'formParameters': None, 'headers': None, 'notNull': None, 'example': None, 'sche
ma': None}

Kind Regards,
Wouter van der Beek

**Comment by WAvdBeek** [comment]
found the issue:
basically the RAML language can have more than one body defined as payload each having its own schema definition.
this level seems to be not there in the parser (parse_body function)
hence adding skipping of the level will fill in the parse tree.
however the storage of the parse tree does not has the level of indirection of the schema, but has only one body in the parse tree. this should be adapted that it should be a dict of schema's in the body (e.g. the responses do have this indirection).

the quick fix (for my situation) is to add the lines:
    # dirty fix
    c = ParseContext(c.get("application/json"), c.relative_path)

in the parse_body function.
this leaves the current parse tree intact and parses the schema and examples etc..

def parse_body(c):
    """
    Parse and extract resource with name

    :param c:ParseContext object which contains RamlBody
    :type c: ParseContext

    :return: RamlMethod  or None
    :rtype: RamlMethod
    """

    if c.data is None:
        return None
    
    body = RamlBody()

    # dirty fix
    c = ParseContext(c.get("application/json"), c.relative_path)

    body.example = c.get_string_property("example")
    
    _body = c.get("body")
    # Parse not null `body` inline property
    if _body:
        body.body = parse_body(ParseContext(_body, c.relative_path))

    body.schema = c.get_string_property("schema")
    body.example = c.get_string_property("example")
    body.formParameters = c.get_property_with_schema("formParameters", RamlBody.formParameters)
    body.headers = c.get_property_with_schema("headers", RamlBody.headers)

    return body

**Comment by an2deg** [comment]
Hi Wouter!

I have fixed this issue. Please try latest code from master branch and let me known.

**Comment by WAvdBeek** [comment]
Hi Andrii

sorry for my late reply but I was on a short break.
I have tried the latest version but that fails parsing the attached file.

can you take a look
(I still can continue by using my patch...)

Kind Regards,
Wouter

On 01/02/2015 20:04, Andrii Degtiarov wrote:
>
> Hi Wouter!
>
> I have fixed this issue. Please try latest code from master branch and 
> let me known.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/an2deg/pyraml-parser/issues/12#issuecomment-72381343>.
>


#%RAML 0.8
title: putexample
version: v1.0


/putexample:
    description: description put
    displayName: exampleexmaple
    put:
        body:
            description: put body description
            application/json:
                schema: |
                    { "$schema": "http://json-schema.org/schema",
                        "vxxx" : { "type": "string" }
                    }    
        responses:    
            200:
                description: 200 response description
                body:
                    application/json:
                        schema: |
                            { "$schema": "http://json-schema.org/schema",
                              "rt": { "type": "string", "required":true },
                              "if": { "type": "string", "required":true },
                              "resourcelinks": {
                                "link": { "type": "string" }
                                }
                            }
