### ISSUE TITLE
TypeError: 'RamlRoot' object is not callable

### ISSUE THREAD

**Issue by BrightZliu** [an2deg/pyraml-parser#24]
from flask import Flask
app = Flask(__name__)
import pyraml.parser

@app.route("/")
def hello():
        p= pyraml.parser.load('schema.raml')
        return p

if __name__ == "__main__":
    app.run(host='0.0.0.0',port=8087,debug=True,threaded=True)

it throws an exception, did I miss something?

TypeError
TypeError: 'RamlRoot' object is not callable

Traceback (most recent call last)
File "/Library/Python/2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Library/Python/2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Library/Python/2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Library/Python/2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
response = self.make_response(rv)
File "/Library/Python/2.7/site-packages/flask/app.py", line 1577, in make_response
rv = self.response_class.force_type(rv, request.environ)
File "/Library/Python/2.7/site-packages/werkzeug/wrappers.py", line 841, in force_type
response = BaseResponse(*_run_wsgi_app(response, environ))
File "/Library/Python/2.7/site-packages/werkzeug/test.py", line 867, in run_wsgi_app
app_rv = app(environ, start_response)
TypeError: 'RamlRoot' object is not callable

**Comment by an2deg** [comment]
Hi!

Could you provide your schema.raml? It would be very helpful for
reproducing this bug.

Best regards,

**Comment by BrightZliu** [comment]
#%RAML 0.8
title: Amazon simple storage API
version: 1
baseUri: https://{destinationBucket}.s3.amazonaws.com
/:
  post:
    description: The POST operation adds an object to a specified bucket using HTML forms.
    body:
      application/x-www-form-urlencoded:
        formParameters:
          AWSAccessKeyId:
            description: The AWS Access Key ID of the owner of the bucket who grants an Anonymous user access for a request that satisfies the set of constraints in the Policy.
            type: string
          acl:
            description: Specifies an Amazon S3 access control list. If an invalid access control list is specified, an error is generated.
            type: string
          file:
            - type: string
              description: Text content. The text content must be the last field in the form.
            - type: file
              description: File to upload. The file must be the last field in the form.


BTW, it could work via shell command like 
>>> import pyraml.parser
>>> p= pyraml.parser.load('schema.raml')
>>> print p
{'title': 'Amazon simple storage API', 'baseUri': 'https://{destinationBucket}.s3.amazonaws.com', 'documentation': None, 'mediaType': None, 'securitySchemes': None, 'resourceTypes': None, 'version': 1, 'resources': OrderedDict([('/', {'displayName': None, 'methods': OrderedDict([('post', {'body': OrderedDict([('application/x-www-form-urlencoded', {'notNull': None, 'formParameters': OrderedDict([('AWSAccessKeyId', {'repeat': None, 'displayName': None, 'name': None, 'default': None, 'pattern': None, 'enum': None, 'maximum': None, 'required': None, 'minimum': None, 'minLength': None, 'maxLength': None, 'type': 'string', 'example': None, 'description': 'The AWS Access Key ID of the owner of the bucket who grants an Anonymous user access for a request that satisfies the set of constraints in the Policy.'}), ('acl', {'repeat': None, 'displayName': None, 'name': None, 'default': None, 'pattern': None, 'enum': None, 'maximum': None, 'required': None, 'minimum': None, 'minLength': None, 'maxLength': None, 'type': 'string', 'example': None, 'description': 'Specifies an Amazon S3 access control list. If an invalid access control list is specified, an error is generated.'}), ('file', [{'repeat': None, 'displayName': None, 'name': None, 'default': None, 'pattern': None, 'enum': None, 'maximum': None, 'required': None, 'minimum': None, 'minLength': None, 'maxLength': None, 'type': 'string', 'example': None, 'description': 'Text content. The text content must be the last field in the form.'}, {'repeat': None, 'displayName': None, 'name': None, 'default': None, 'pattern': None, 'enum': None, 'maximum': None, 'required': None, 'minimum': None, 'minLength': None, 'maxLength': None, 'type': 'file', 'example': None, 'description': 'File to upload. The file must be the last field in the form.'}])]), 'example': None, 'schema': None})]), 'description': 'The POST operation adds an object to a specified bucket using HTML forms.', 'queryParameters': None, 'headers': None, 'notNull': None, 'baseUriParameters': None, 'protocols': None, 'responses': None})]), 'description': None, 'uriParameters': None, 'is_': None, 'baseUriParameters': None, 'type': None, 'resources': None, 'securedBy': None})]), 'traits': None, 'baseUriParameters': None, 'raml_version': u'0.8', 'protocols': ['HTTPS'], 'schemas': None}

**Comment by an2deg** [comment]
Hi,

I think you should return either string or Response object. I don't know
what should be on output of your view function (Json encoded object?)

Best regards,
