### ISSUE TITLE
Defining JSON body using native RAML?

### ISSUE THREAD

**Issue by relaxdiego** [an2deg/pyraml-parser#3]
I understand that RAML doesn't define a standard for JSON payloads and, instead, falls back to JSONSchema for that. However, having to switch between RAML and JSONSchema is disorienting and can lead to a few typos down the line. I would rather just use RAML throughout my schemas if I can. I understand that I should probably post this in the RAML forums but I'm curious to know what are your thoughts on this?

**Comment by postatum** [comment]
Hi @relaxdiego 
Thanks for bringing up this topic. I agree with everything @fireantology said :)
But i think the better place to discuss this would be RAML forums.

Thanks

**Comment by relaxdiego** [comment]
Thanks for the responses. I'd forgotten about this question until I got the notification. I also found that the RAML is working on making this happen: https://github.com/raml-org/raml-spec/issues/116
