### ISSUE TITLE
uriParameters support

### ISSUE THREAD

**Issue by econchick** [an2deg/pyraml-parser#6]
Hi there!  

I noticed that this library does not support `uriParameters` per the [RAML spec](http://raml.org/spec.html#toc_34).  Is there any intention to?

Thanks!

**Comment by postatum** [comment]
Hi @econchick ,

Support for root ``baseUriParameters`` and methods' ``uriParameters`` have been added, though it's only in the repo yet.

As for root ``uriParameters`` - that property is not valid, as forums say http://forums.raml.org/t/baseuriparameters-vs-root-uriparameters/315/2

**Comment by econchick** [comment]
Great - thanks so much!
